// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnayal3r-Q_-yIQwjkNswofVMTN8JFT4Y',
    appId: '1:234618679519:web:f3b00ae473c9b3f2b6396a',
    messagingSenderId: '234618679519',
    projectId: 'yuuto-c22aa',
    authDomain: 'yuuto-c22aa.firebaseapp.com',
    storageBucket: 'yuuto-c22aa.appspot.com',
    measurementId: 'G-YYWGJ3TTDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwl55j3W2Dtf0WxAg7rB369Y6G6zcwFU',
    appId: '1:234618679519:android:eaf0c1cc2a7493c2b6396a',
    messagingSenderId: '234618679519',
    projectId: 'yuuto-c22aa',
    storageBucket: 'yuuto-c22aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR4Yr199zs4bCU5pRyosKbbYBpsb80IRU',
    appId: '1:234618679519:ios:36cff02c9651ca0eb6396a',
    messagingSenderId: '234618679519',
    projectId: 'yuuto-c22aa',
    storageBucket: 'yuuto-c22aa.appspot.com',
    iosClientId: '234618679519-citoh9hdk1cjv4t3hkqlqvu3mtj00g80.apps.googleusercontent.com',
    iosBundleId: 'com.example.tttest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR4Yr199zs4bCU5pRyosKbbYBpsb80IRU',
    appId: '1:234618679519:ios:36cff02c9651ca0eb6396a',
    messagingSenderId: '234618679519',
    projectId: 'yuuto-c22aa',
    storageBucket: 'yuuto-c22aa.appspot.com',
    iosClientId: '234618679519-citoh9hdk1cjv4t3hkqlqvu3mtj00g80.apps.googleusercontent.com',
    iosBundleId: 'com.example.tttest',
  );
}
